### ISSUE TITLE
train_cls.py error

### ISSUE THREAD

**Issue by reddittoob** [naurril/DeepAnnotate#1]
Hi, thank you for sharing your project.

I'm trying to train classification model.

I made all_obj.npy using prepare_data_kitti.py.

However, I got an error like below.

  File "/home//anaconda3/envs/pointnet_keras/lib/python3.6/site-packages/tensorflow_core/python/ops/linalg_ops_impl.py", line 57, in eye
    'num_rows and num_columns must be positive integer values.')
TypeError: num_rows and num_columns must be positive integer values.

Can you help me?

**Comment by naurril** [comment]
can you provide the full error output? As I don't see the calling point of prepare_data_kitti.py

**Comment by reddittoob** [comment]
Here is full error output.

Traceback (most recent call last):
  File "train_cls.py", line 72, in <module>
    train()
  File "train_cls.py", line 26, in train
    model = M.get_model_cls(common.NUM_POINT, common.NUM_CLASSES[2], True)
  File "/home/data/DeepAnnotate/model.py", line 77, in get_model_cls
    x = get_backbone(input_pointcloud, num_point, is_training)
  File "/home/data/DeepAnnotate/model.py", line 45, in get_backbone
    trans = transform_net(x, is_training)
  File "/home/data/DeepAnnotate/model.py", line 37, in transform_net
    x = tf.add(x, tf.reshape(tf.eye(K), [-1,]))
  File "/home/anaconda3/envs/pointnet_keras/lib/python3.6/site-packages/tensorflow_core/python/ops/linalg_ops.py", line 169, in eye
    name=name)
  File "/home/anaconda3/envs/pointnet_keras/lib/python3.6/site-packages/tensorflow_core/python/ops/linalg_ops_impl.py", line 57, in eye
    'num_rows and num_columns must be positive integer values.')
TypeError: num_rows and num_columns must be positive integer values.

**Comment by naurril** [comment]
did you change any code? it seems that the `all_objs.npy` has  problem

**Comment by reddittoob** [comment]
I didn't change code and I used kitti dataset.
I don't know what I have to do.
And, I have a question more. How do I make a sustechscape_all_objs.npy file?
I don't have "sustechscapes-mini-dataset/lidar" data.
Also, I tried to register my information for getting sustechscapes data, but I got an error like below image.

![Screenshot from 2022-08-22 17-37-54](https://user-images.githubusercontent.com/30588581/185878029-7a3d5036-45eb-4117-9280-ede696b7d471.png)

**Comment by reddittoob** [comment]
I resolved this problem.
This problem occurred because of my tensorflow version. 
In tensorflow 1.15 version, I can't load my gpu, but after I changed my version, your scripts are working well now. However, I can't still download sustech dataset.
Thank you.
